// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		User:              newUser(db, opts...),
		UserFollow:        newUserFollow(db, opts...),
		UserVideo:         newUserVideo(db, opts...),
		UserVideoFavorite: newUserVideoFavorite(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	User              user
	UserFollow        userFollow
	UserVideo         userVideo
	UserVideoFavorite userVideoFavorite
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		User:              q.User.clone(db),
		UserFollow:        q.UserFollow.clone(db),
		UserVideo:         q.UserVideo.clone(db),
		UserVideoFavorite: q.UserVideoFavorite.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		User:              q.User.replaceDB(db),
		UserFollow:        q.UserFollow.replaceDB(db),
		UserVideo:         q.UserVideo.replaceDB(db),
		UserVideoFavorite: q.UserVideoFavorite.replaceDB(db),
	}
}

type queryCtx struct {
	User              *userDo
	UserFollow        *userFollowDo
	UserVideo         *userVideoDo
	UserVideoFavorite *userVideoFavoriteDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		User:              q.User.WithContext(ctx),
		UserFollow:        q.UserFollow.WithContext(ctx),
		UserVideo:         q.UserVideo.WithContext(ctx),
		UserVideoFavorite: q.UserVideoFavorite.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
