// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"MicroTikTok/user/model/dao/model"
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newUserVideo(db *gorm.DB, opts ...gen.DOOption) userVideo {
	_userVideo := userVideo{}

	_userVideo.userVideoDo.UseDB(db, opts...)
	_userVideo.userVideoDo.UseModel(&model.UserVideo{})

	tableName := _userVideo.userVideoDo.TableName()
	_userVideo.ALL = field.NewAsterisk(tableName)
	_userVideo.UserID = field.NewInt32(tableName, "user_id")
	_userVideo.VideoID = field.NewInt32(tableName, "video_id")

	_userVideo.fillFieldMap()

	return _userVideo
}

type userVideo struct {
	userVideoDo userVideoDo

	ALL     field.Asterisk
	UserID  field.Int32
	VideoID field.Int32

	fieldMap map[string]field.Expr
}

func (u userVideo) Table(newTableName string) *userVideo {
	u.userVideoDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userVideo) As(alias string) *userVideo {
	u.userVideoDo.DO = *(u.userVideoDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userVideo) updateTableName(table string) *userVideo {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewInt32(table, "user_id")
	u.VideoID = field.NewInt32(table, "video_id")

	u.fillFieldMap()

	return u
}

func (u *userVideo) WithContext(ctx context.Context) *userVideoDo {
	return u.userVideoDo.WithContext(ctx)
}

func (u userVideo) TableName() string { return u.userVideoDo.TableName() }

func (u userVideo) Alias() string { return u.userVideoDo.Alias() }

func (u userVideo) Columns(cols ...field.Expr) gen.Columns { return u.userVideoDo.Columns(cols...) }

func (u *userVideo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userVideo) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 2)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["video_id"] = u.VideoID
}

func (u userVideo) clone(db *gorm.DB) userVideo {
	u.userVideoDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userVideo) replaceDB(db *gorm.DB) userVideo {
	u.userVideoDo.ReplaceDB(db)
	return u
}

type userVideoDo struct{ gen.DO }

func (u userVideoDo) Debug() *userVideoDo {
	return u.withDO(u.DO.Debug())
}

func (u userVideoDo) WithContext(ctx context.Context) *userVideoDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userVideoDo) ReadDB() *userVideoDo {
	return u.Clauses(dbresolver.Read)
}

func (u userVideoDo) WriteDB() *userVideoDo {
	return u.Clauses(dbresolver.Write)
}

func (u userVideoDo) Session(config *gorm.Session) *userVideoDo {
	return u.withDO(u.DO.Session(config))
}

func (u userVideoDo) Clauses(conds ...clause.Expression) *userVideoDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userVideoDo) Returning(value interface{}, columns ...string) *userVideoDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userVideoDo) Not(conds ...gen.Condition) *userVideoDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userVideoDo) Or(conds ...gen.Condition) *userVideoDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userVideoDo) Select(conds ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userVideoDo) Where(conds ...gen.Condition) *userVideoDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userVideoDo) Order(conds ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userVideoDo) Distinct(cols ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userVideoDo) Omit(cols ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userVideoDo) Join(table schema.Tabler, on ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userVideoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userVideoDo) RightJoin(table schema.Tabler, on ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userVideoDo) Group(cols ...field.Expr) *userVideoDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userVideoDo) Having(conds ...gen.Condition) *userVideoDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userVideoDo) Limit(limit int) *userVideoDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userVideoDo) Offset(offset int) *userVideoDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userVideoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userVideoDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userVideoDo) Unscoped() *userVideoDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userVideoDo) Create(values ...*model.UserVideo) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userVideoDo) CreateInBatches(values []*model.UserVideo, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userVideoDo) Save(values ...*model.UserVideo) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userVideoDo) First() (*model.UserVideo, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVideo), nil
	}
}

func (u userVideoDo) Take() (*model.UserVideo, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVideo), nil
	}
}

func (u userVideoDo) Last() (*model.UserVideo, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVideo), nil
	}
}

func (u userVideoDo) Find() ([]*model.UserVideo, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserVideo), err
}

func (u userVideoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserVideo, err error) {
	buf := make([]*model.UserVideo, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userVideoDo) FindInBatches(result *[]*model.UserVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userVideoDo) Attrs(attrs ...field.AssignExpr) *userVideoDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userVideoDo) Assign(attrs ...field.AssignExpr) *userVideoDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userVideoDo) Joins(fields ...field.RelationField) *userVideoDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userVideoDo) Preload(fields ...field.RelationField) *userVideoDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userVideoDo) FirstOrInit() (*model.UserVideo, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVideo), nil
	}
}

func (u userVideoDo) FirstOrCreate() (*model.UserVideo, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserVideo), nil
	}
}

func (u userVideoDo) FindByPage(offset int, limit int) (result []*model.UserVideo, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userVideoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userVideoDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userVideoDo) Delete(models ...*model.UserVideo) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userVideoDo) withDO(do gen.Dao) *userVideoDo {
	u.DO = *do.(*gen.DO)
	return u
}
