// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"MicroTikTok/comment/rpc/internal/logic"
	"MicroTikTok/comment/rpc/internal/svc"
	"MicroTikTok/comment/rpc/pb/comment"
)

type CommentActionServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentActionServer
}

func NewCommentActionServer(svcCtx *svc.ServiceContext) *CommentActionServer {
	return &CommentActionServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentActionServer) CommentList(ctx context.Context, in *comment.CommentListReq) (*comment.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}

func (s *CommentActionServer) CommentAction(ctx context.Context, in *comment.CommentActionReq) (*comment.CommentActionResp, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}
