// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"MicroTikTok/user/rpc/internal/logic"
	"MicroTikTok/user/rpc/internal/svc"
	"MicroTikTok/user/rpc/rpc/user"
)

type UserInfoServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserInfoServer
}

func NewUserInfoServer(svcCtx *svc.ServiceContext) *UserInfoServer {
	return &UserInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *UserInfoServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserInfoServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserInfoServer) UserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
