// Code generated by goctl. DO NOT EDIT.
// Source: favoritelist.proto

package server

import (
	"context"

	"MicroTikTok/favoritelist/rpc/internal/logic"
	"MicroTikTok/favoritelist/rpc/internal/svc"
	"MicroTikTok/favoritelist/rpc/pb/favoritelist"
)

type FavoriteListServer struct {
	svcCtx *svc.ServiceContext
	favoritelist.UnimplementedFavoriteListServer
}

func NewFavoriteListServer(svcCtx *svc.ServiceContext) *FavoriteListServer {
	return &FavoriteListServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteListServer) FavoriteList(ctx context.Context, in *favoritelist.FavoriteListRequest) (*favoritelist.FavoriteListResponse, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}
