// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserVideo = "user_video"

// UserVideo mapped from table <user_video>
type UserVideo struct {
	UserID  int32 `gorm:"column:user_id;primaryKey" json:"user_id"`
	VideoID int32 `gorm:"column:video_id;primaryKey" json:"video_id"`
}

// TableName UserVideo's table name
func (*UserVideo) TableName() string {
	return TableNameUserVideo
}
