// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserVideoFavorite = "user_video_favorite"

// UserVideoFavorite mapped from table <user_video_favorite>
type UserVideoFavorite struct {
	LikerID int32 `gorm:"column:Liker_id;primaryKey" json:"Liker_id"`
	LikedID int32 `gorm:"column:Liked_id;primaryKey" json:"Liked_id"`
}

// TableName UserVideoFavorite's table name
func (*UserVideoFavorite) TableName() string {
	return TableNameUserVideoFavorite
}
