// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username        string `gorm:"column:username;not null;comment:注册用户名，最长32个字符" json:"username"` // 注册用户名，最长32个字符
	Name            string `gorm:"column:name;not null;comment:用户昵称" json:"name"`                  // 用户昵称
	Password        string `gorm:"column:password;not null;comment:密码，最长32个字符" json:"password"`    // 密码，最长32个字符
	Avatar          string `gorm:"column:avatar;not null" json:"avatar"`
	BackgroundImage string `gorm:"column:background_image;not null" json:"background_image"`
	Signature       string `gorm:"column:signature;not null;default:该用户什么都没留下" json:"signature"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
