// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserFollow = "user_follow"

// UserFollow mapped from table <user_follow>
type UserFollow struct {
	FollowerID int32 `gorm:"column:follower_id;primaryKey" json:"follower_id"`
	FollowedID int32 `gorm:"column:followed_id;primaryKey" json:"followed_id"`
}

// TableName UserFollow's table name
func (*UserFollow) TableName() string {
	return TableNameUserFollow
}
