// Code generated by goctl. DO NOT EDIT.
// Source: favoritelist.proto

package favoritelistclient

import (
	"context"

	"MicroTikTok/favoritelist/rpc/pb/favoritelist"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteListRequest  = favoritelist.FavoriteListRequest
	FavoriteListResponse = favoritelist.FavoriteListResponse
	User                 = favoritelist.User
	Video                = favoritelist.Video

	FavoriteList interface {
		FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...grpc.CallOption) (*FavoriteListResponse, error)
	}

	defaultFavoriteList struct {
		cli zrpc.Client
	}
)

func NewFavoriteList(cli zrpc.Client) FavoriteList {
	return &defaultFavoriteList{
		cli: cli,
	}
}

func (m *defaultFavoriteList) FavoriteList(ctx context.Context, in *FavoriteListRequest, opts ...grpc.CallOption) (*FavoriteListResponse, error) {
	client := favoritelist.NewFavoriteListClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}
